// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.Data;

namespace WebApplication.Data
{
    [DbContext(typeof(Auth))]
    partial class AuthModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebApplication.Data.AppUser", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Roles")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("userId");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            password = "iLoveMax123",
                            username = "Kacper2022"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
